# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85be634b48b34c8165f14fe79994ef66c61c18865971899093a57a3cef15b5be310174d48e90b16f29fe971b9290dc33370cd135c1a971f93848437420b087a1

test:
  secret_key_base: 06164b70757fb630b4d134cfaaaf40a5d16d63e1ab5ab41f5c5039012d9f7e7c26907b8c9e18ad2544ef738efaf7553a56d840c4307d6837a76aed2dcf172eec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
